local packets = {

  out = { -- outgoing
    PACKET_NPC_INTERACTION = 0x1A,
    PACKET_NPC_CHOICE = 0x5B,
  },


  inc = { -- incoming
    PACKET_MENU_INFO = 0x5C,
    PACKET_INCOMING_CHAT = 0x17,
    PACKET_PARTY_STATUS_EFFECT = 0x76,
    PACKET_PARTY_INVITE = 0xDC,
    PACKET_FIELD_MANUAL_RESPONSE = 0x82,
    PACKET_NPC_INTERACTION = 0x32,
    PACKET_NPC_INTERACTION_2 = 0x34,
  },


  INVITE_TYPE_PARTY = 0x0,


  CHAT_TYPE_LINKSHELL2 = 0x1B
};
return packets;
